### ISSUE TITLE
use of stis_cti.StisPixCteCorr.CteCorr on other data

### ISSUE THREAD

**Issue by vpicouet** [spacetelescope/stis_cti#14]
Hello,
I am working on another project (FIREBall https://arxiv.org/abs/2101.01920), on which we also experience poor CTE on an eletron multiplying CCD.
do you know what is the easiest way to apply StisPixCteCorr.CteCorr to our data?
Do you know if this code has been generalized to other (EM)CCDs?
Thanks a lot for your help/time

**Comment by sean-lockwood** [comment]
Hi @vpicouet,

So the STIS correction was derived from an older version of the ACS pixel-based correction.  ACS now uses an updated version, described in [ACS ISR 2018-04](https://www.stsci.edu/files/live/sites/www/files/home/hst/instrumentation/acs/documentation/instrument-science-reports-isrs/_documents/isr1804.pdf).

When we did adapt the older ACS code for use with STIS, the major changes required in the c source were to handle different detector sizes and to rotate the image before/after given different amplifier readout directions.  In any case, more work would probably be spent characterizing the reference file for your detector.

Using the STIS code would require deriving an instrument-specific calibration file similar to the Bedin, et al 2010 procedure, so I'd suggest following the latest ACS procedures and code if you have the option.

From your paper:
> Each impact creates a "tail" in the direction of charge transfer due to deferred and overspill charge in the serial multiplication register.

The HST corrections were designed to correct for parallel CTI.  If the effect you're trying to correct is in the serial direction, I'm not sure how to adapt the code.

I also haven't worked with EMCCDs before, though _perhaps_ the only change required vs a standard CCD would be to the threshold selection due to different counting statistics.

What level of CTI are you seeing on your detector?

**Comment by vpicouet** [comment]
Hello @sean-lockwood,
thanks for your answer! 
Indeed the CTI is high in our amplification register so appears in the serial direction. 
Events create an exponential tail having a characterictic length of ~1.5pix, which means that the first pixel keeps only ~50% of its charges while the following pixels share the second half. 
Using [ACS ISR 2018-04](https://www.stsci.edu/files/live/sites/www/files/home/hst/instrumentation/acs/documentation/instrument-science-reports-isrs/_documents/isr1804.pdf) formula this would mean CTE = 1 ~ 0.5 Q / (1000xQ) = 0.9995 I think.

I just began to play with [arctic](https://github.com/jkeger/arctic) which seems to do the same CTE correction but which seems more easily usable on other format images.
This is what I manage to correct with two set of traps (density=[10,12], release timescale=[0.2,0.7])

![slit_corrected_d10 0_t0 2](https://user-images.githubusercontent.com/37241971/163296934-56792618-03b7-418c-b5dd-5fcd2ff5710d.png)

I will read the different papers you sent, to see if I manage to create a reference file for our detector.
I add an image where the smearing is pretty obvious (in the -x direction).
[test_image_smearing_.fits.zip](https://github.com/spacetelescope/stis_cti/files/8485700/test_image_smearing_.fits.zip)

Thanks again for your help!
